### ISSUE TITLE
Rajouter les méthodes isFlush, is3OfAKind et isStraight à la classe Milestone

### ISSUE THREAD

**Issue by Liloubhe** [schotten-totten-company/schotten-totten-core#1]
Je pense que dans les manipulations de mon IA je vais souvent faire des tests pour savoir si j'ai une combinaison intéressante dans la main. Il serait probablement plus structuré d'implémenter ces méthodes au niveau de la classe (et de pouvoir les tester au sens MilestoneTests). Parce que j'ai l'impression qu'on définit ce genre de choses déjà à deux endroits différents (Milestone l176 et GameAiLucieImpl l49) et que la duplication c'est le mal ! ;-)

**Comment by bastienbarthet** [comment]
corrected by commit 8c51894dac274630b6366d04359f94d621949257
